# 新交易使用情况统计
sheet = "新交易使用情况"
start_col = "A"
query = """\
select a.jym,jymc,c.ywbm,c.lxr,zbs,hzbs from gbsqb a
left join (select jym,sum(zbs)as hzbs from gbsqb group by jym) b on a.jym=b.jym
left xjdz c on a.jym=c.jym
where length(a.jym)=5 and yf = (select max(yf) from gbsqb)
order by zbs desc
"""

[widths]
"A" = 10
"B" = 40
"C" = 40
"D" = 15
"E:F" = 15

[[column]]
name = "交易码"
total_string = "总计"

[[column]]
name = "交易名称"

[[column]]
name = "业务部门"

[[column]]
name = "联系人"

[[column]]
name = "当月交易笔数"
format = "Number"
total_function = "sum"

[[column]]
name = "累计交易笔数"
format = "Number"
total_function = "sum"
